kind: "BuildConfig"
apiVersion: "v1"
metadata:
  name: "java-app-pipeline"
spec:
  source:
    type: "Git"
    git:
      uri: "https://github.com/jgoldsmith613/rh-summit-security-2017.git"
      ref: "symposium"
  strategy:
    type: "JenkinsPipeline"
    jenkinsPipelineStrategy:
      jenkinsfilePath: "java-app/Jenkinsfile"
  triggers:
   - type: "imageChange"
     imageChange:
       from:
         kind: "ImageStreamTag"
         name: "java:prod"
