apiVersion: v1
kind: BuildConfig
metadata:
  name: java-app
spec:
  output:
    to:
      kind: ImageStreamTag
      name: java-app:latest
  source:
    binary: {}
    type: Binary
  strategy:
    sourceStrategy:
      from:
        kind: ImageStreamTag
        name: java:prod
    type: Source
  triggers: []
