kind: "BuildConfig"
apiVersion: "v1"
metadata:
  name: "java-base-layer-pipeline"
spec:
  source:
    type: "Git"
    git:
      uri: "https://github.com/jgoldsmith613/rh-summit-security-2017.git"
      ref: "september-webinar"
  strategy:
    type: "JenkinsPipeline"
    jenkinsPipelineStrategy:
      jenkinsfilePath: "base-layer-java/Jenkinsfile"
