node( 'maven' ) {

    stage('checkout'){
        checkout scm
    }

    stage('unit test'){}
    stage('sonar scan'){}

    stage('trigger build'){
        login()
        sh """
            cd java-app
            mkdir -p s2i/deployments
            mvn package dependency:copy-dependencies -Popenshift -DskipTests -e
            mv target/dependency/* s2i/deployments/.
            mv target/*.jar s2i/deployments/. 
            oc start-build java-app --from-dir=s2i --follow=true
        """
    }

}

podTemplate(label: 'mypod', cloud: "openshift", containers: [
    containerTemplate(name: 'java-app-slave', image: '172.30.135.69:5000/rh-summit-2017/java-app:latest', ttyEnabled: true, command: 'cat')
  ]) {

node( 'mypod'){

container(name: 'java-app-slave', cloud: "openshift"){

  stage('Build Application Scan'){
      sh 'mv /deployments/* .'
      nexusPolicyEvaluation failBuildOnNetworkError: false, iqApplication: 'security', iqStage: 'build', jobCredentialsId: ''
      if (currentBuild.result == 'UNSTABLE'){
          input 'Application has been marked as having a Sonatype policy violation.  Please check build logs, or iq server (http://iqserver-nexus.apps.c3.core.rht-labs.com).  Do you wish to proceed anyway?'
      }
  }
  

  stage('smoke test') {
  }
  stage('deploy to dev') {}
  stage('Release Application Scan'){
      nexusPolicyEvaluation failBuildOnNetworkError: false, iqApplication: 'security', iqStage: 'release', jobCredentialsId: ''
      if(currentBuild.result == 'FAILURE'){
          error("Sonatype policy violations not allowed in PROD")
      }
      
  }
  stage('deploy to prod') {
     input 'Promte to Prod?'
  }
}

}
}


def login() {
    sh """
       set +x
       oc login --certificate-authority=/var/run/secrets/kubernetes.io/serviceaccount/ca.crt --token=\$(cat /var/run/secrets/kubernetes.io/serviceaccount/token) https://kubernetes.default.svc.cluster.local >/dev/null 2>&1 || echo 'OpenShift login failed'
       """
}






